# Generated by Django 5.1.2 on 2024-10-16 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brand_alter_car_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='nome',
            new_name='name',
        ),
    ]
